# Generated by Django 4.2.1 on 2023-05-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Адреса')),
                ('telephone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.CharField(max_length=50, verbose_name='e-mail')),
            ],
        ),
    ]
